### ISSUE TITLE
Reverb system not returning a listing which already exists in the system

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#102]
There's a product with sku image_sync in the system. When I save the product, forcing a listing sync, the Reverb system won't return the listing via the api/my/listings?state=all&sku=image_sync API call, but the I'm receiving error "You already have a listing with the SKU image_sync. Please use a unique SKU." when I call api/listings --data {"sku":"image_sync","title":...}. Below are the log data for the calls

findReverbListingUrlByMagentoSku
state=all&sku=image_sync
200
{"total":0,"_links":{},"listings":[]}

createObject
{"title":"Image Sync Test","sku":"image_sync","description":"Image Sync Test","condition":"Used","has_inventory":"1","inventory":"313213.0000","price":"12.0000"}
412
{"message":"Please fill in all the fields required for submitting your listing to the marketplace.","listing":{"make":"Unknown","model":"Image Sync Test","finish":"","title":"Image Sync Test","description":"Image Sync Test","price":{"amount":"12.00","currency":"USD","symbol":"$"},"offers_enabled":false,"_links":{"photo":{"href":"https://da1wmtc5ur1xq.cloudfront.net/assets/products/blank_medium-19ba00051c336ac75f04e103a1ae310b.jpg"},"self":{"href":"/api/listings/-image-sync-test"},"update":{"method":"PUT","href":"/api/listings/-image-sync-test"},"end":{"method":"PUT","href":"/api/my/listings/-image-sync-test/state/end"},"want":{"method":"PUT","href":"/api/wants/-image-sync-test"},"unwant":{"method":"DELETE","href":"/api/wants/-image-sync-test"},"edit":{"href":"/api/listings/-image-sync-test/edit"},"web":{"href":"https://sandbox.reverb.com/item/-image-sync-test"},"add_to_wishlist":{"method":"POST","href":"/api/my/wishlist/-image-sync-test"},"remove_from_wishlist":{"method":"DELETE","href":"/api/my/wishlist/-image-sync-test"},"flag":{"href":"/api/listings/-image-sync-test/flag"},"contact_seller":{"web":{"href":"https://sandbox.reverb.com/my/messages/new?item=-image-sync-test\u0026to=98-magento%40test.com"}},"conversations":{"href":"/api/listings//conversations"},"shop":{"href":"/api/shops/hane-inc","web":{"href":"https://sandbox.reverb.com/shop/hane-inc"}}},"accepted_payment_methods":["direct_checkout","paypal"],"location":{"country_code":"US","locality":"Chicago","region":"IL"},"has_inventory":false,"draft":true,"live":false,"cloudinary_photos":[],"shop":{"feedback_count":0,"preferred_seller":false,"rating_percentage":0.0},"stats":{"views":0,"watches":0},"offer_count":0,"shipping_policy":"I will ship with tracking to the continental United States. Alaska, Hawaii, and international shipments may incur additional charges.","payment_policy":"To negotiate price, shipping, or payment options, please send a message or make an offer.","is_my_listing":false,"photos":[],"shipping":{"us":false,"rates":[]},"seller":{"paypal_email":"thomas@runte.biz"}},"errors":{"sku":["You already have a listing with the SKU image_sync. Please use a unique SKU."]}}

The CURL logs:
2015-09-24T04:34:11+00:00 DEBUG (7): 
curl -XGET -H "X-Auth-Token: 1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c" -H "Content-type: application/hal+json" -H "X-Magento-Version: Community-1.9.2.0" -H "X-Magento-Domain: reverb_magento.com" -H "X-Reverb-App: magento" https://sandbox.reverb.com/api/my/listings?state=all&sku=image_sync 
2015-09-24T04:34:55+00:00 DEBUG (7): 
curl -XPOST -H "X-Auth-Token: 1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c" -H "Content-type: application/hal+json" -H "X-Magento-Version: Community-1.9.2.0" -H "X-Magento-Domain: reverb_magento.com" -H "X-Reverb-App: magento" https://sandbox.reverb.com/api/listings --data {"title":"Image Sync Test","sku":"image_sync","description":"Image Sync Test","condition":"Used","has_inventory":"1","inventory":"313213.0000","price":"12.0000"}

**Comment by dunagan5887** [comment]
Also seeing this with skus create_with_image_againdadsa and create_with_image_again. Both were first created within the past hour

**Comment by skwp** [comment]
probably inconsistent indexing state on our side. I will investigate

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by skwp** [comment]
Yeah our indexing is messed up. I'm trying to fix it up right now

**Comment by skwp** [comment]
this should be fixed

**Comment by skwp** [comment]
Closing this as it's fixed on our side
