### ISSUE TITLE
Image Sync Revamp

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#109]
- A new image_sync queue task object will be created. Each image_sync queue task will transmit 1 image to Reverb
- The image_sync queue task will be on the unique task table. The unique_id will be a concatentation of the sku and the catalog_product_entity_media_gallery table value_id field (the primary key on that table)
- Upon listing creation, an image_sync queue task will be created for each gallery image on the product. No photos will be included in the actual listing creation API call
- Upon the product after_save event, if a new gallery image was created on the product, a new image_sync queue task will be created for that image

**Comment by skwp** [comment]
as per discussion in chat let's make sure we key off of the unique magento gallery id and use the filename as a column that's not necessarily searchable

**Comment by dunagan5887** [comment]
"use the filename as a column that's not necessarily searchable"

By this do you mean you won't want to be able to search by filename? By putting into the database table, we get sorting and filtering on that column for free in the grids

**Comment by skwp** [comment]
search by file name is good to have 

--
Yan Pritzker
yanpritzker.com
via iPhone
