### ISSUE TITLE
Put title, quantity, and price sync behind switches

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#111]
We need these switches:

* enable_title_sync (label: "Sync title on update, magento->Reverb") - default NO
* enable_price_sync(label: "Sync price on update, magento->Reverb") - default NO
* enable_quantity_sync(label: "Sync inventory on update, magento->Reverb") - default YES

Then the code in ~/dev/reverb-magento/app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php needs to be modified to use these switches

This is so that sellers who change their prices on reverb are not impacted. For now I have disabled title and price sync by commenting it out in #110

**Comment by dunagan5887** [comment]
Noticing that you commented out condition in the updateObject() method as well. Should that be behind an update switch or just removed completely?

**Comment by skwp** [comment]
I just removed condition on update since we don't even have a field for it..it's just this global thing

**Comment by dunagan5887** [comment]
Sounds good
