### ISSUE TITLE
rev_sync attribute should be named sync_to_reverb to be intuitive

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#115]
Currently the "Sync to Reverb" attribute code is `rev_sync`, which is somewhat unclear.  I'd suggest using `sync_to_reverb` to align with the UI name and to at least make it explicit that it's a Reverb attribute.

**Comment by skwp** [comment]
Yes, we have a number of "legacy" named attributes that we can rename, thanks we'l keep this in mind.

**Comment by skwp** [comment]
closing this out, the PR is out there if at some point we have time to add a migration
