### ISSUE TITLE
Reverb_ReverbSync_Helper_Sync_Product::getReverbSyncEligibleProductIds() and its usages are extremely inefficient

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#118]
`Reverb_ReverbSync_Helper_Sync_Product::getReverbSyncEligibleProductIds()` retrieves all Product Ids in Magento before then excluding those for which Reverb is disabled.  It does so by loading each product individually; in our scenario (10's of thousands of SKUs, Reverb enabled for a small fraction of them) this is an extremely inefficient and resource intensive approach.

The method should execute a query which returns only products which have Reverb Sync enabled.  The ORM is *not* slower than a direct SQL query for this type of lookup.

**Comment by skwp** [comment]
:+1:

**Comment by skwp** [comment]
Fixed in #119
