### ISSUE TITLE
Set listing condition on a per-listing basis (condition as attribute on product)

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#120]
The Product Condition is currently configured via the ReverbSync system configuration; using the same value for all products.  The configuration should add the option to map the allowed values to a Magento attribute.

Pseudo-story:

As a Magento Store Owner
In order to list products in various conditions to Reverb
I want to specify the condition to be used for all listings
Or I want to specify a Product Attribute which stores the Condition
And I want to map the Magento Attribute Values to Reverb's Conditions

E.g.
Use 'condition' as the attribute, passing 'Brand New' when the condition of a product is 'New'

**Comment by skwp** [comment]
And the condition should be a dropdown list rather than an arbitrary value as these will fail if they don't   match exactly what Reverb wants

**Comment by skwp** [comment]
This is the list
       "Non functioning"
       "Poor"
       "Fair"
       "Good"
       "Very good"
       "Excellent"
       "Mint"
       "Like New"
       "Brand New"

**Comment by skwp** [comment]
@StevenWolfe are you planning to do work on this one? i think it's a pretty easy one to knock out but my developer (sean)'s time is limited over the next week

**Comment by StevenWolfe** [comment]
I'll probably put together a stopgap for our needs.  If it's anything worth
sharing I'll pass it along, but it might just be a quick hack to get us
running.

**Comment by skwp** [comment]
Ok thanks

**Comment by dunagan5887** [comment]
@skwp If Reverb expects the condition to match one of the strings you provided above, does it make sense to take values from a product attribute that an admin can choose? Would it make more sense to create a reverb_condition product attribute with the fixed values above for this purpose? Or should I just set the API call not to include the condition field if the condition value doesn't match that list above?

**Comment by skwp** [comment]
Yeah they should choose from a list rather than type it in, that would be better, thanks

**Comment by dunagan5887** [comment]
Does capitalization matter in that list above? Is ""Very good" supposed to be ""Very Good"?

**Comment by skwp** [comment]
we accept any capitalization although Very Good is the new correct one (everything is ProperCased)

**Comment by dunagan5887** [comment]
Should this be included on both listing creation and update? Or just creation?

**Comment by skwp** [comment]
I woudl say both, if condition changes we should change it
