### ISSUE TITLE
ReverbSync generates exception, warning message when saving a Product for which Sync to Reverb = No

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#121]
When a product with Sync to Reverb = No is saved the user is shown an error/warning which states: 

> The "Sync to Reverb" value for this product has been set to "No"; this product can not be synced to Reverb as a result

This may be informational, but is not a standard Magento practice.

Internally this is the result of the product save event triggering an attempt to sync the product; this results in an exception being thrown from `Reverb_ReverbSync_Helper_Sync_Product::executeIndividualProductDataSync()`.  This method will require the product to be loaded an additional time, and could have significant performance and resource ramifications during bulk imports.  The event should use an early-exit rather than attempting a sync.

**Comment by skwp** [comment]
Agreed. If you have a patch for this it would be much appreciated

**Comment by StevenWolfe** [comment]
I'll put together a partial fix; there's still a scalability issue around the event listeners and the check to see if event should trigger a Sync.
