### ISSUE TITLE
Imported orders are created under "Admin" Store View instead of default Store View

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#126]
Reverb's imported orders are being created under the "Admin / Default / Admin" Store View (visible in the Order's "Purchased From" field).  Our orders are normally created under "Main Website / Main Website Store / Default Store View".

This has the effect of assigning the orders different order and invoice numbers.  Such as "000000102" rather than the expected "100041655".  This appears to have some impact on other third-party modules as well, although it appears relatively benign.

**Comment by StevenWolfe** [comment]
it appears that the orders are being created under a different store context; the "Purchased From" field is diplaying "Admin / Default / Admin" whereas "Main Website / Main Website Store / Default Store View" is our normal store.

**Comment by skwp** [comment]
What is more correct? The order was not made on the "Main website" so maybe that's why it's different?

**Comment by StevenWolfe** [comment]
I'll have to defer to @dunagan5887, in our configuration all orders (whether from M2E, the website, or manually entered) use the Default Store View.  I'll double-check the impact of the unexpected order numbers with Jeff when he's available--it's a convention that all our orders begin with 1000*, so there's the chance that these orders will be overlooked somewhere in his excel magic.

**Comment by skwp** [comment]
We can also look at the difficulty of making that value (order view) configurable. Or you guys can just fork and modify the code where appropriate, it's probably a small change?

**Comment by skwp** [comment]
if M2E uses default store view we may want to follow that model for consistency as many customers do use M2E

**Comment by StevenWolfe** [comment]
it may be best to have it be configurable (a dropdown to select from define store views).  Some M2E configurations use separate Store Views for pricing and customer group segmentation by marketplace.

**Comment by dunagan5887** [comment]
Given that the orders are created with via admin interaction or via the crontab, they default to the admin store. It definitely makes sense to allow that to be a configurable option though; I would model this after the way the admin panel's Create Order functionality sets the store_id on the Mage_Adminhtml_Model_Session_Quote _initSession() method. Let me know if you want me to implement this or if you want to handle it

**Comment by StevenWolfe** [comment]
I'lll see if I can make the change this afternoon; turns out our shipping software won't import orders placed against this Store View, so it's a blocking bug for us.

**Comment by skwp** [comment]
@StevenWolfe are you planning to make it configurable then?

**Comment by StevenWolfe** [comment]
I'll aim to; otherwise I'll override it in another module for now
