### ISSUE TITLE
Refunded / cancelled orders are not cancelled in Magento

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#130]
If a paid, ready to ship order is imported to Magento, then cancelled on Reverb the Magento Order import will not pick up on the change and will leave the order in a "Processing" (cleared to ship) state

**Comment by skwp** [comment]
We are only updating the Reverb Status on the order right now, because we weren't sure we should get so deep into a customer's process to start triggering other things on their side. What do you think is the right answer here?

**Comment by StevenWolfe** [comment]
I'll give it some more thought, but my usual preference is to always try to maintain a tight sync when integrating systems.

**Comment by skwp** [comment]
We're working on this over the next week hopefully
