### ISSUE TITLE
sql errors after last update (multi-store dropdown?)

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#136]
I am seeing this in my listing sync grid:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1, query was: SELECT `main_table`.* FROM `re...	

The exception is cut off and I can't tell where the rest is. The error does not appear in my logs. I'm going to try to revert the multi store dropdown

**Comment by dunagan5887** [comment]
The following pull request contains a fix for this issue:
https://github.com/reverbdotcom/reverb-magento/pull/138

**Comment by skwp** [comment]
:+1:
