### ISSUE TITLE
SUPEE-6788 / APPSEC-1034 Admin Routing Updates

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#142]
Magento's [SUPEE-6788 / APPSEC-1034](http://magento.com/security/patches/supee-6788-technical-details) security patch requires all extensions to use proper routes for admin controllers.  It appears that the Reverb controllers will need to be updated to close this security hole.

This is based on the current admin URLs being in the form of: `https://{base_url}/reverbSync/...` whereas they'll need to use the `admin` router: `https://{base_url}/admin/reverbSync/...`

**Comment by StevenWolfe** [comment]
This is based on a cursory review.  Been swimming in patching up fires and squashing bugs related to this patch for 2+ weeks now.  Fun times...

**Comment by skwp** [comment]
Thanks for the heads up. cc @dunagan5887

**Comment by dunagan5887** [comment]
Just looked at this patch and WOW, by far the most labor intensive patch they've come out with. Glad I'm not a full-time agency dev

**Comment by dunagan5887** [comment]
That being said this will take some substantial work, I'll have to look this over in the coming week

**Comment by StevenWolfe** [comment]
Yeah, it's been hell.  It broke 50+ extensions on us; literally thousands
of patches.  We're stemming the bleeding and racing on a full rebuild
rather than patching up legacy.

**Comment by skwp** [comment]
@dunagan5887 when you get a chance could you please give a brief summary of what potential security issues we have with our current code base in light of this page?

**Comment by dunagan5887** [comment]
Ya, I'm going to start on this later today at some point. I'll debrief once I go over the patch in greater detail

**Comment by skwp** [comment]
thanks :+1:
