### ISSUE TITLE
Reverb Orders need to have all address fields trimmed to pass Magento validation

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#143]
We received an order where the Reverb customer's name, street address, and locality had a space on the end of the field, like:

    {
      "name": "John Doe ",
      "street_address": "123 Road ",
      "extended_address": "",
      "locality": "Waffle House ",
      "region": "TX",
      "postal_code": "12345",
      "country_code": "US",
      "phone": "1234567890"
    }

The Magento Order failed to be created due to address validation errors.  The trailing spaces were removed and the order successfully was created.

@skwp perhaps this is an API change rather than Magento?

**Comment by skwp** [comment]
Yep We can fix this in the Api but it's a strange reason to fail.  Magento is a strange beast. 

Thanks for reporting please keep it up

**Comment by StevenWolfe** [comment]
Strange beast indeed&ndash;it never makes sense, and is never simple.  Two years in and I'm ready to get back to the real world away from PHP and Magento.

Sorry for the wall of issues; just finally getting a break from a couple weeks of fires.  Hoping to get some pull requests in for some of these odds and ends before long.

**Comment by skwp** [comment]
Filing this as an API side fix. Keeping issue open until we fix it.

**Comment by dunagan5887** [comment]
I suppose we could additionally put in code to run trim() on any/all fields returned from Reverb, this may help alleviate any issues related to whitespaces

**Comment by skwp** [comment]
Yeah that coudl be good as a fix here, thanks
