### ISSUE TITLE
Handling for Local Pickup orders (no address in magento)

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#144]
We've had several orders imported which have not yet had a shipping address provided by the customer in Reverb.  Off the cuff I can think of two solutions&ndash;both aren't great:

1. Add a configurable address to the extension's configuration options which can be used as a placeholder when an address hasn't been provided.  This has the benefit of creating the order in Magento immediately and updating the product's availability, but the extension (currently) won't ever retrieve the actual address once it's been provided.

2. Prevent the extension from retrieving orders without addresses, perhaps showing a warning that some orders haven't yet been imported.  This creates inventory drift, but would prevent the orders from becoming stuck in the import process.

**Comment by dunagan5887** [comment]
@skwp are shipping addresses required for an order to be shipped in Reverb? If so I would recommend solution 2 from a technical perspective

**Comment by skwp** [comment]
Some orders are local pickup which does not require an address. Is that what's happening or are you talking about offer based orders? We have a big out to prevent orders from getting invoiced until they are paid

**Comment by dunagan5887** [comment]
Based on this, it sounds like we may want solution 1: allowing merchants to define the shipping address which is attached to a shipping order. Once the order is created, an admin could go into the system and edit the order to whatever the specific local pickup address is

**Comment by StevenWolfe** [comment]
This came up with Order #719857, which was for a listing without local pickup.  The order was picked up by the sync queue before an address or payment was provided, so it became stuck in an Error state.

Option 1 would be preferred to avoid overselling; we would setup an obvious address (i.e. "CHECK REVERB FOR ADDRESS") to use as a placeholder.

Local pickup might warrant a second configurable address for order imports.

**Comment by skwp** [comment]
a fake address can be confusing. Let's be explicit.  If it's local pickup it should specifically say local pickup in the address field if that's a problem for magento

Also for offers that don't yet have an address we can put in an explicit adress saying 'awaiting address at time of payment'. Additionally we will not magento invoice the unpaid order in a fix coming soon

Yan

**Comment by dunagan5887** [comment]
Once we have the fix to prevent orders from being automatically invoiced, will there still be a need for action here?

**Comment by StevenWolfe** [comment]
@dunagan5887 this will still be an issue.  An order can't be created without an address, regardless of its payment status

**Comment by skwp** [comment]
So the fix we need here is for local_pickup orders, set the address to "Local Pickup" or whatever is required to satisfy magento's requirements internally

**Comment by dunagan5887** [comment]
@skwp Can you create an order for my test account which has local pickup, meaning there's no address included in the JSON? Also, what values should I use for the City/State/Zip in this case?

**Comment by skwp** [comment]
I would just put "Local Pickup" in all fields. If it must be numeric use 0000 or whatever for the zip. What's your account email?

**Comment by skwp** [comment]
You can also create your own orders by using an incognito window and creating a new reverb account on sandbox.reverb.com and buying your own item with fake credit card 4111 1111 1111 1111

**Comment by dunagan5887** [comment]
Pretty sure my account is below:

magento@test.com / password
1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c

**Comment by dunagan5887** [comment]
The region field will be required. If a valid region is required, which state should I use?

**Comment by skwp** [comment]
you can use "IL"

**Comment by skwp** [comment]
oh you mean for fake data?

**Comment by skwp** [comment]
does it have to be a real place?

**Comment by dunagan5887** [comment]
It doesn't have to be a real address, just needs to have valid values for each field

**Comment by skwp** [comment]
Order 112 is now local_pickup / no address

I would use the value "Local Pickup" whenever possible

**Comment by dunagan5887** [comment]
Amazingly Magento somehow allowed me to set every field in the address to "Local Pickup" (I copied the buyer_name field to the address name though). Can't believe it was allowed, it doesn't look great, but it works. I'm going to test this on 1.7 before creating a PR
