### ISSUE TITLE
Suggestion: Change verbiage for order sync statuses to differ from Magento order statuses

### ISSUE THREAD

**Issue by StevenWolfe** [reverbdotcom/reverb-magento#146]
This is low priority, but came to mind from the comment-thread in the discussion of #134.

The Reverb order sync tasks have a Status column.  The values currently used are:

 - Pending (the sync task hasn't yet executed)
 - Processing (the sync task is being executed)
 - Complete (the sync task has completed successfully)
 - Error
 - Failed

Magento Orders also have a Status attribute, which is used to describe where the order is in the fulfillment lifecycle.  Three of these statuses overlap with the Reverb sync task statuses:

 - Pending (the order has been created, but payment not yet received)
 - Processing (the order has been paid for and is ready for fulfillment)
 - Complete (the order has been shipped)

While there is no technical issue here it is somewhat confusing, especially when seeing them on the Reverb Order Sync grid, next to the Reverb Order ID column.  Having sync statuses which differ from the stock Magento Order statuses would avoid this confusion.  Perhaps:

 - Sync-Pending
 - Synchronizing
 - Success

**Comment by skwp** [comment]
:+1:

**Comment by skwp** [comment]
thanks for the idea. I'll take a PR for this but we're not scheduling this as official work at this time.
