### ISSUE TITLE
addFieldIfNotEmpty bug

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#162]
Recoverable Error: Argument 3 passed to Reverb_Reports_Model_Reverbreport::_addFieldIfNotEmpty() must be of the type array, null given, called in app/code/community/Reverb/Reports/Model/Reverbreport.php on line 58 and defined  in 
app/code/community/Reverb/Reports/Model/Reverbreport.php on line 68

**Comment by skwp** [comment]
Not sure about the severity or cause of this

**Comment by dunagan5887** [comment]
Not sure what would cause this, I don't think it's too severe. Is there a stack trace with the error message?

**Comment by skwp** [comment]
i lost the logs from this, will let you know if it happens again
