### ISSUE TITLE
Package for magento connect

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#17]
Make extension installable from Magento Connect and document process of updating the extension

**Comment by dunagan5887** [comment]
What's the timeline for this task? Did you want this to come after all testing for the Order Sync has been completed? Also Reverb will need to create a Magento Developer account and grant me access to it

**Comment by skwp** [comment]
This is the last thing after we do image sync and category mapping

**Comment by skwp** [comment]
I'll  set up the account
