### ISSUE TITLE
unable to list Magento product in Reverb

### ISSUE THREAD

**Issue by achyuthi95dev** [reverbdotcom/reverb-magento#175]
Hi,

I have created new product in Magento and listing to Reverb while listing it was throwing an issue
"Call to undefined method Reverb_ReverbSync_Model_Adapter_Curl::setOptions()" this setOptions() method was not declared in following path app/code/community/Reverb/ReverbSync/Model/Adapter/Curl.php

Please help me how to go head on above issue

Regards
Achyuth

**Comment by skwp** [comment]
Hi guys. We'll try to address this as quickly as possible. @dunagan5887 is this a possible php version issue?

**Comment by dunagan5887** [comment]
@skwp Could be a PHP version issue or it could be a Magento version issue. What versions of PHP and Magento are the client on?

**Comment by skwp** [comment]
PHP Version 5.3.24
Magento EE 1.11.0

**Comment by skwp** [comment]
Is this possibly a case of php not having the curl lib installed?
