### ISSUE TITLE
Field mapping

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#179]
This is a requested feature by several customers. They have structured make/model fields as well as special price fields. They are requesting the ability to map Reverb fields to their magento fields, so that on the settings screen we would have a Field Mapping section that looked something like

```
Reverb Field             Magento Field
-----------------------------------------------
make                         [dropdown of product fields]
model                        [dropdown of product fields]
price                        [dropdown of product fields]
```

All fields should default to their current values (we already send price, but we don't send make & model)

**Comment by dunagan5887** [comment]
Do you have API documentation on how these custom fields should be sent?

**Comment by skwp** [comment]
We're already sending make/model fields, they're commented out in ReverbSync/Model/Mapper/Product.php line 71/72. Can you please estimate the work for this? Thanks!

**Comment by dunagan5887** [comment]
If we're just talking about these 3 attributes, I can make System -> Configuration values for these and it will take about 3-4 hours. If more of these types of fields are going to be added in the future, then we would want to start thinking about adding an additional database table and page in the admin panel. That would be more extensive.

**Comment by skwp** [comment]
I'm ok with adding the system level attributes for now unless there will be a big pain migrating them later. What's the limitation with continuing to add static fields? Realistically there's a limit to about 10 fields that we would ever want to map.

**Comment by dunagan5887** [comment]
10 System-Config level attributes should be fine. Once the basic functionality for these fields is implemented, additional fields shouldn't take more than an hour or two if all done at once.

Again, estimating between 3-4 hours for this update

**Comment by skwp** [comment]
I'm good with that, go ahead with the update, thanks.
