### ISSUE TITLE
Support for configurable products

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#180]
I would like to understand what's involved with taking a configurable product (e.g. tshirts with multiple sizes) and sending them to Reverb as individual entries. The assumption is that each will have a unique SKU (is this always true?)

**Comment by dunagan5887** [comment]
Yes, each simple product which is part of a configurable product will have a unique SKU. I would estimate about 3-4 hours for this update

**Comment by dunagan5887** [comment]
@skwp If the configurable product has images which are not on the child products, those configurable-only images will not be communicated to Reverb. Additionally only data related to the simple products will be sent to Reverb (only simple products are sent). Is this acceptable?

**Comment by skwp** [comment]
The idea here is that every configurable variation should be like the parent. So the images _should_ appear on all children. Not sure what you mean by simple products being sent?

The way I see it is you hav ea Tshirt with S/M/L variants. This should result in 3 different products on Reverb, one for each variation, each with the images of the parent if the children don't have images.

**Comment by dunagan5887** [comment]
Simple product means child product. Am I supposed to be sending child and parent products to Reverb? Sending parent products wouldn't make much sense given that they don't have inventory. 

So if the child product doesn't have images, then the parent's images should be sent?  What if the child product does have images attached?

**Comment by skwp** [comment]
understood. yes I would say send the child's images if you have them, if not use the parent's images for each child

**Comment by dunagan5887** [comment]
Right, my concern here is that there's a chance that people could have the same images on the parent as on the child, which would cause in the same image being sent to Reverb multiple times

**Comment by skwp** [comment]
Yeah we should not combine images. either the child has images and we use only those or we use the ones from the parent if the child is empty.

**Comment by dunagan5887** [comment]
Scenario:

- Admin creates configurable product
- Admin uses the Quick Create feature in the Associated Products tab to create a simple product
- The system sees that there are no images for the simple product so it transmits the parent's images for this child
- The admin then adds images for the child product
- The images are added for the child product, and may be the same images as were transmitted in item 3 of this scenario

I'm not sure how to address this issue, and no fix would be quick/clean.

**Comment by dunagan5887** [comment]
Scenario:

- Admin creates configurable product
- Admin uses the Quick Create feature in the Associated Products tab to create a simple product
- During the child product's save, the child is not yet associated with the parent product. As such, the parent product's images will not be communicated to Reverb until the child product is saved individually

I'm not sure how to address this issue, and no fix would be quick/clean.

**Comment by dunagan5887** [comment]
Scenario:

- Admin creates configurable product
- Admin adds image(s) to the configurable product
- Admin uses the Quick Create feature in the Associated Products tab to create child products for the parent
- Admin Saves the configurable product
- All image(s) added to the configurable parent will be sent to Reverb for all child products
- Admin adds an image for a child product
- The child product will now have the parent's image and it's own image on Reverb

I have confirmed this happening. At the moment I don't have a quick fix for how to go about this. I'm not sure a clean solution exists. The best would be to unlist the parent images once the image has been attached to the child

**Comment by skwp** [comment]
I'm ok with this. Sellers can clean up their own images by hand for this scenario
