### ISSUE TITLE
Migrate rev_product_id and other rev fields labels

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#182]
in  app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-install-0.1.0.php

there are several attributes which were originally poorly labeled with "Rev Product id", "Rev Product URL"

I'd like a migration that changes just their labels to be "Reverb Listing Id" and "Reverb Listing URL". 

I'm assuming actually renaming those columns is more difficult, but if it's not it would be nice to change rev_product_id to reverb_product_id and rev_product_url to reverb_product_url as well as rev_sync to reverb_sync_enabled

The main reason for this is that these attributes are now being exposed as of #179 to the customers

**Comment by zztimur** [comment]
Yan, are you talking to @dunagan5887, or is this community message?

**Comment by skwp** [comment]
@zztimur hey good to hear from you :) This is an open source project so issues are going to be public. I am looking to implement a migration to make the attribute names easier to understand

**Comment by zztimur** [comment]
@skwp I see you merged some stuff. I'd need to bump the version of the extension to make those changes. Can you release new version with the new changes, say v.0.8.0 and then I can implement those updates in 0.8.1. It'll be available today.

By version I mean the magento versioning.

**Comment by skwp** [comment]
Not sure what you're asking about. This issue is just an open issue, there are no code changes. The 0.8.0 release will be put out tomorrow containing field mapping and configurable product support. There has not been any code released related to this issue (renaming fields)

**Comment by zztimur** [comment]
Magento triggers database updates on a version bump.
