### ISSUE TITLE
Image sync

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#19]
when syncing product listing to reverb, sync all the images. We have no way to delete images right now so if there are issues around figuring out which images have been synced, we can implement some API to wipe out all existing images.

**Comment by dunagan5887** [comment]
Assumptions:
1. This sync is sending images FROM Magento TO Reverb
2. There will be a system configuration setting "Enable Product Image Sync with Reverb" which is a Yes/No
3. A new page will be created under Catalog (eventually presumed to be under a new Reverb menu item) which contains a "Bulk Product Image Sync" button.
4. When this button is pressed, an image sync background queue task will be created for every product which does not currently have an image sync task in the database. 
5. Another "Resync All Products" button will allow the user to create a background sync task for every product which does not currently have an image sync task in the database. For every product which already has an image sync task in the database, the status of that task will be updated to pending.
6. The image sync will only sync the product's Base Image with Reverb

**Comment by dunagan5887** [comment]
@skwp After looking at http://dev.reverb.com/docs/create-a-listing, should I make the image sync a separate task from the current listing sync? Or should I just include that field in with the listing sync? Or only include it with the listing sync if the admin just changed the base image field of the product?

**Comment by skwp** [comment]
can we get all the images not just the first one?

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
Given that we need to implement this using a separate queue task for image_sync, this will take between 5-7 hours. Whenever a listing sync (Create or Update) is executed, a check will be made to see which images on the product do not have an associated image sync object in the database. Any images without such an object will have one create to queue up the sync of the image

**Comment by dunagan5887** [comment]
Unfortunately I'm not sure I'll be able to address this today or tomorrow. I may have to work on it Sunday night. I will hopefully have it ready to go Monday morning

**Comment by skwp** [comment]
One thing to note is this going to cause N requests one for each image with a photos array of 1 image?

**Comment by skwp** [comment]
Ok are you able to for now just remove the update code so we only sync them on listing create then I can actually ship it to people while you work on the other stuff for next week?

**Comment by dunagan5887** [comment]
"One thing to note is this going to cause N requests one for each image with a photos array of 1 image?"
Yes, this would be the end result.

"are you able to for now just remove the update code so we only sync them on listing create"
Yes, this is a quick fix I will patch up

My 5-7 hours estimate will not implement the most efficient solution in terms of performance (shouldn't be a performance killer either in the grand scheme of things though) but it will be the quickest stable architecture approach

**Comment by skwp** [comment]
Closing this out, i tink we can call it done

**Comment by dunagan5887** [comment]
Agreed on calling it done
