### ISSUE TITLE
magento mass  attribute update does not trigger Reverb updates

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#201]
if using magento's mass attribute update, we do not trigger reverb updates. Customers are forced to hit bulk sync.

**Comment by dunagan5887** [comment]
So the goal here is to have mass attribute trigger a bulk sync?

**Comment by dunagan5887** [comment]
And it should trigger regardless of whether the updated attributes are relevant to Reverb or not? For instance if only 1 attribute was updated and it's not an attribute being sent to Reverb?

**Comment by dunagan5887** [comment]
I have pushed a commit for this but haven't been able to fully test it yet

**Comment by zztimur** [comment]
@dunagan5887 Yes, because currently if you do mass attribute update, reverb sync isn't queued at all.
What magento event are you using as a trigger? product_attribute_save_after ?

**Comment by skwp** [comment]
Ideally it only syncs the products that have changed meaningful to reverb but it would be fine to sync all

**Comment by zztimur** [comment]
Ideally there should be a pre-sync logic that would check

**Comment by dunagan5887** [comment]
Currently triggering this on catalog_product_attribute_update_before. This event does pass the attributes data to the observers, so I could put in a pre-sync logic check to inspect which attributes are being updated. I imagine that if the client has mapped Magento attributes to the Reverb Make/Model/Price fields, those attributes should be considered as relevant correct?
