### ISSUE TITLE
When saving magento product, reverb sync should be backgrounded

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#207]
This seems strange - if reverb is slow/down it will affect the magento save of the product in the catalog. Is this how other plugins are done? I think we should be backgrounding this

cc @zztimur @dunagan5887 @StevenWolfe

**Comment by dunagan5887** [comment]
This was done this way partially due to the legacy code that we were working with/around. Currently the Bulk Product sync button queues up background tasks to sync listings. We could have that same functionality queue up a single product's listing in a background task. This would be a 1-2 hour max

**Comment by zztimur** [comment]
@dunagan5887 for some reason bulk sync doesn't work for me.
I haven't checked why yet

**Comment by skwp** [comment]
Yes I think this should be done thanks

**Comment by skwp** [comment]
@zztimur is your cron ok?

**Comment by skwp** [comment]
@dunagan5887 this is at the top of my list, the only one I'm concerned about right now

**Comment by dunagan5887** [comment]
@skwp Should I also background the product listing sync during the Order Save?

**Comment by skwp** [comment]
yes we should not block magento in general from normal path operations

**Comment by dunagan5887** [comment]
There was the following comment in the code which referenced exceptions thrown while executing the product listing sync during product save

`// Any other Exception is understood to prevent product save`

Do we want the failure to queue a listing sync to prevent product save? (There's no normal reason this would happen, it would signify a serious issue with the module or Magento instance)

Given this update, an exception during background processing of the listing sync will no longer prevent product save

**Comment by skwp** [comment]
This is correct, our plugin should never interfere with a customer's critical path to saving a product for their own purposes. The background task can be retried at a later time

**Comment by skwp** [comment]
i.e. whatever code is there should be considered legacy; we should not prevent a product save by any means

**Comment by dunagan5887** [comment]
@skwp There was logic in place which prevented listing creations from being executed during the order placement event observer (listings would only be updated). Should this logic remain?

**Comment by dunagan5887** [comment]
@zztimur The Bulk Sync is working on my local, it's queue-ing up image listing syncs as well. Let me know what you find if you look into it

**Comment by zztimur** [comment]
Images don't seem to sync. figuring it out. from my logs:

2016-02-25T01:21:14+00:00 ERR (3): 
exception 'Exception' with message 'Error executing task for queue task object with id 535: The API call returned an HTTP status that was not 200: 502.
URL: https://sandbox.reverb.com/api/my/listings?state=all&sku=ODS-060
Content: 
Curl Error Message: ' in /chroot/home/thedjhoo/dev2.thedjhookup.com/html/.modman/reverb-magento/app/code/community/Reverb/ProcessQueue/Helper/Task/Processor.php:230
Stack trace:
#0 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/.modman/reverb-magento/app/code/community/Reverb/ProcessQueue/Helper/Task/Processor.php(102): Reverb_ProcessQueue_Helper_Task_Processor->_logError('Error executing...')
#1 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/.modman/reverb-magento/app/code/community/Reverb/ProcessQueue/Helper/Task/Processor.php(36): Reverb_ProcessQueue_Helper_Task_Processor->processQueueTask(Object(Reverb_ProcessQueue_Model_Task_Unique))
#2 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/.modman/reverb-magento/app/code/community/Reverb/ReverbSync/Model/Cron/Listings/Images/Sync.php(19): Reverb_ProcessQueue_Helper_Task_Processor->processQueueTasks('listing_image_s...')
#3 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/.modman/reverb-magento/app/code/community/Reverb/Process/Model/Locked/Cron/Abstract.php(45): Reverb_ReverbSync_Model_Cron_Listings_Images_Sync->executeCron()
#4 [internal function]: Reverb_Process_Model_Locked_Cron_Abstract->attemptCronExecution(Object(Aoe_Scheduler_Model_Schedule))
#5 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/app/code/community/Aoe/Scheduler/Model/Observer.php(79): call_user_func_array(Array, Array)
#6 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#7 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#8 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#9 /chroot/home/thedjhoo/dev2.thedjhookup.com/html/cron.php(76): Mage::dispatchEvent('default')
#10 {main}

**Comment by skwp** [comment]
@zztimur that looks like a temporary sandbox issue. are you getting that repeatedly? can I see the reverb curl log?

@dunagan5887 i'm not sure what you mean by listing creations being blocked during order placement. what is the impact of that? what do orders have to do with listings?

**Comment by dunagan5887** [comment]
When an order is placed, there was an event observer which executed a listing sync with reverb (presumably to update the inventory count on Reverb). If the listing had already been created on Reverb it would be updated. However if the sku had not been listed on Reverb, the listing would not be created as a result of this order placement observer

**Comment by skwp** [comment]
Yes that seems like a bug. If listing creation is enabled in settings then any update to reverb should first check if the listing exists and if not, create it. All updates regardless of whether they are order syncs or anything else should go through this flow.

**Comment by zztimur** [comment]
I'll send you errors (if any) once we test it again.

On Thu, Feb 25, 2016 at 10:04 AM, Yan Pritzker <notifications@github.com>
wrote:

> Yes that seems like a bug. If listing creation is enabled in settings then
> any update to reverb should first check if the listing exists and if not,
> create it. All updates regardless of whether they are order syncs or
> anything else should go through this flow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reverbdotcom/reverb-magento/issues/207#issuecomment-188854274>
> .
>



-- 
-- Sent from my iPhone
