### ISSUE TITLE
Settings update product attributes

### ISSUE THREAD

**Issue by zztimur** [reverbdotcom/reverb-magento#209]
There are settings to update title, description, price.

@skwp 
So if you set not to udpate title, product titles wouldn't be updated.
Is this suppose to be like that? can't really understand why.
And why only 3 attributes?

**Comment by skwp** [comment]
Because some people only want to update inventory and have reverb titles separate from magento titles. Reverb has stricter standards for titles, so sometimes they want to edit reverb titles to clean them up. Same story on the other attributes. This is not a bug, thanks.

**Comment by zztimur** [comment]
@skwp Yes, but make/model is not included in those settings.
Does it make sense to have a setting, such as "sync product data" - yes/no?

**Comment by skwp** [comment]
No, we find that people want individual control over those fields. There are too many different needs to group them under one switch. Make/model are typically not the issue. It's that people want to have different titles/descriptions/prices on reverb. This is built based on customer needs. Not looking to simplify that right now, thanks

**Comment by zztimur** [comment]
I get it.
Asked to better understand.
