### ISSUE TITLE
Setting to enable/disable order sync (default: disabled)

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#21]
Order sync should be off by default. Add setting to toggle it on off (Yes/No option). Label should say "Sync orders from Reverb to Magento"

**Comment by dunagan5887** [comment]
Reverb_ReverbSync_Helper_Orders_Retrieval::_retrieveOrdersJsonFromReverb()

Need to update this to only retrieve the past 24 hours

**Comment by dunagan5887** [comment]
@skwp  I assume that the order update process should also respect this setting?

**Comment by skwp** [comment]
yep

--
Yan Pritzker
yanpritzker.com
via iPhone
