### ISSUE TITLE
ACL in Category SyncController

### ISSUE THREAD

**Issue by daved** [reverbdotcom/reverb-magento#210]
The following has been added to our installation to allow non-admin users access to the Catalog Mapper:
```
protected function _isAllowed()
{
    return Mage::getSingleton('admin/session')->isAllowed($this->getControllerActiveMenuPath());
}
```
A pull request didn't seem to make sense due to my inexperience with the project, and because there may already be some ACL changes in progress.  What might we expect regarding this in the future?

**Comment by skwp** [comment]
this is done
