### ISSUE TITLE
Global configuration option for a default free shipping

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#218]
specifically so customers can set all listings to be free shipping

**Comment by zztimur** [comment]
I think we should also per product attribute. Does that make sense?

**Comment by skwp** [comment]
I would like to avoid per-product here because we actually have multi region shipping support, so you can ship to CONUS vs hawaii or alaska or euro countries at different rates. There isn't really a sane way to do that per product. Instead we ask people use our Shipping Profiles feature to set up per-category profiles (on Reverb). I'm thinking this feature is more of a "free shipping on everything to my local region" checkbox

**Comment by skwp** [comment]
To clarify that comment, if we implement per-product shipping then technically people should be putting in multiple region per product so filling out an entire matrix per product. it's very inefficient and impractical. shipping profiles are the solution to that problem

**Comment by skwp** [comment]
I think we'll handle this by implementing the shipping_profile_name option so we can map to a reverb shipping profile that is free shipping. See also #222 #230
