### ISSUE TITLE
Button to trigger Order Sync (on Bulk Sync page)

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#22]
Let's have everything in one place. A button to start the order sync and if possible indicator of the sync being in progress if we know that to be the case.

If the sync is finished it would be ideal to display "Last sync ran at [timestamp]". Same for bulk product sync. But if this data is hard to come by, omit it.

**Comment by dunagan5887** [comment]
This button will trigger both order creations and updates, correct?

**Comment by dunagan5887** [comment]
Also should this be on it's own page accessible via Sales -> Reverb Sync Orders in the admin panel? You don't want this included on the Listing Sync page right?

**Comment by skwp** [comment]
Sure that's fine if that's what other plugins do. Is it confusing that Reverb functionality is across multiple menus?

**Comment by dunagan5887** [comment]
I don't think so. In my opinion it would be more confusing if Order Sync was under the Catalog menu

**Comment by skwp** [comment]
Sounds good

**Comment by dunagan5887** [comment]
Do you want to list the amount of order/listing syncs which were aborted or are in error state?

Aborted tasks will not be re-attempted (e.g. Order which was already synced)
Errored tasks will be re-attempted (e.g. unknown exceptions)
