### ISSUE TITLE
Cron to trigger order sync (every 5 mins)

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#23]
Let's check for new orders every 5 mins. The creator cron should happen every minute (?)

**Comment by dunagan5887** [comment]
This button will trigger both order creations and updates, correct?

**Comment by skwp** [comment]
Correct

**Comment by skwp** [comment]
Although technically you're going to get duplication since updates will also contain the creates

**Comment by skwp** [comment]
yes

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
Due to memory considerations I'm going to limit the amount of orders which can be created by one execution thread to be 100. I am not limiting the amount of orders which can be queued for creation/update
