### ISSUE TITLE
Magento sends list with empty string for category mapping sometimes: [""]

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#236]
We are seeing this in some requests

category_uuids:[""]

In other words it's an array with one element, which is an empty string. This is not a valid mapping. If no mappings are present we should send an empty array.

**Comment by dunagan5887** [comment]
@skwp Should I begin work on this one?

**Comment by skwp** [comment]
Yes if this is a quick thing please let's knock it out

**Comment by dunagan5887** [comment]
Looking at the code I'm not sure how this would be happening on the current version of the module. I can put in a fix to try to prevent this, but that would not address whatever deeper issue is causing this issue. Is there any way we could get a database dump for one of the instances sending these requests? Also could you provide the entire requests which contains the empty category_uuids array?
