### ISSUE TITLE
Reverb Orders without an address should still be created

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#237]
The orders should be created with the value "No Address" populating all fields

**Comment by dunagan5887** [comment]
@kylecrum Entering the value of "No Address" for the country field will result in "Norway" being shown in the admin panel Order Edit screen. Is that acceptable or should I change the country_code to be US?

**Comment by kylecrum** [comment]
@dunagan5887 can that be blank so that it shows the default? (I'm guessing it shows norway because that's the closest to "No Address".)

**Comment by dunagan5887** [comment]
If no value is entered, the address will fail validation. For some reason, the value of "Local Pickup" does not show any country in the admin panel. Should I just choose some value that doesn't have an associated country?

**Comment by kylecrum** [comment]
@dunagan5887 Ideally, ya.

**Comment by dunagan5887** [comment]
The empty country code patch is now on this branch

**Comment by kylecrum** [comment]
@dunagan5887 is the code ready to go? Can you make a PR if it is?
