### ISSUE TITLE
Products with SKUs containing special characters are not being synced correctly

### ISSUE THREAD

**Issue by zztimur** [reverbdotcom/reverb-magento#238]
If you have a product with an SKU with a special character it won't sync correctly.

Here's an example. We had a product with a TAB symbol somehow ending up being part of SKU.
Say SKU in magento is "product-abcd<TAB>".
Here's what happens to it.

1. Initial sync goes fine. The products sku is sent to reverb as "product-abcd\t"
2. Inventory updates -> Queued for re-sync.
3. On re-sync module checks if the product exists in the reverb via api using url containing the sku that is url encoded. So it checks for "product-abcd%9".
4. Obviously product with such sku doesn't exist, so module attempts to create a new listing for product with sku "product-abcd\t"
5. We get an error "SKU already exists in your shop. SKUs must be unique.already exists in your shop. SKUs must be unique." (fix the error message by the way).

**Comment by zztimur** [comment]
So since we are doing calls via urls, it makes sense to url encode the sku for reverb. I'll post a pull request shortly.

**Comment by kylecrum** [comment]
Is this fixed by this PR? https://github.com/reverbdotcom/reverb-magento/pull/239 @zztimur ?

**Comment by zztimur** [comment]
Yes

**Comment by skwp** [comment]
Please see discussion here: https://github.com/reverbdotcom/reverb-magento/pull/242 I don't think your fix did what you think it shoudl do. You only need to urlencode the GET request

**Comment by zztimur** [comment]
@skwp Any news from your team? Was this tested on API?

**Comment by skwp** [comment]
We will be fixing the tab problem on our side probably by next week or sooner

**Comment by kylecrum** [comment]
@zztimur should be fixed on our end.

**Comment by zztimur** [comment]
awesome thanks
