### ISSUE TITLE
Shipment tracking doesn't sync

### ISSUE THREAD

**Issue by zztimur** [reverbdotcom/reverb-magento#248]
Error:
"An error occurred while attempting to queue shipment tracking sync with Reverb for tracking object with id xxxx: Serialization of 'SimpleXMLElement' is not allowed"

**Comment by zztimur** [comment]
@dunagan5887 

reverb-magento/app/code/community/Reverb/ReverbSync/Helper/Shipment/Data.php triggers the error.

`    /**
     * @param Mage_Sales_Model_Order_Shipment_Track $shipmentTrackingObject
     * @return Reverb_ProcessQueue_Model_Task_Unique|null
     */
    public function queueShipmentTrackingSyncIfReverbOrder(Mage_Sales_Model_Order_Shipment_Track $shipmentTrackingObject)
    {
        try
        {
            if (!$this->isTrackingForAReverbOrderShipment($shipmentTrackingObject))
            {
                return null;
            }
            $trackingSyncQueueTaskObject = $this->queueShipmentTrackingSyncWithReverb($shipmentTrackingObject);
            return $trackingSyncQueueTaskObject;
        }
        catch(Exception $e)
        {
            // We shouldn't be catching anything here. If we do, a PHP level exception likely occurred
            $tracking_id = is_object($shipmentTrackingObject) ? $shipmentTrackingObject->getId() : null;
            $error_message = $this->__(self::EXCEPTION_QUEUE_TRACKING_SYNC, $tracking_id, $e->getMessage());
            $this->logError($error_message);
        }
        return null;
    }`

**Comment by dunagan5887** [comment]
I haven't seen that one before. Could you send me a sanitized version of whatever Reverb is communicating to Magento?

**Comment by zztimur** [comment]
@dunagan5887 
I isolated the issue.
It only happens when shipment is added via Shipstation.
Shipstation supplies with its magento extension Auctane_Shipstation.
It works via API. Whenever you create a shipment in Shipstation, it calls your website via API.
Attaching the Model that handles the update of creating shipment for the order.

Could you take a look?
[Shipnotify.txt](https://github.com/reverbdotcom/reverb-magento/files/242904/Shipnotify.txt)

**Comment by dunagan5887** [comment]
It seems to me like the Auctane_Api_Model_Action_Shipnotify::process() should be converting the $xml->TrackingNumber, $xml->Carrier to strings before setting them on the $track object. Magento expects that strings are given in these fields, not SimpleXmlElement objects.

**Comment by dunagan5887** [comment]
Without having any data to test with that seems to be the most likely cause of the issue

**Comment by zztimur** [comment]
Probably all of the values should be cast to an appropriate type before setting.

**Comment by dunagan5887** [comment]
I would agree
