### ISSUE TITLE
Q: Adding prefix to reverb orders

### ISSUE THREAD

**Issue by zztimur** [reverbdotcom/reverb-magento#250]
What do you think of adding prefix to reverb orders in magento?

**Comment by kylecrum** [comment]
Maybe? What are you thinking? Not sure of the use case here.

**Comment by zztimur** [comment]
Example: M2E extension most popular for handling eBay and amazon sync, uses
prefixes in front of orders number.
Use case: easily distinguish sales channel - things can be handled
differently for magento sales vs external sale.

So instead of "1000049494" order would be "R-1000049494" or something like
that (for reverb).

On Tue, May 3, 2016 at 5:24 PM, Kyle Crum <notifications@github.com> wrote:

> Maybe? What are you thinking? Not sure of the use case here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/reverbdotcom/reverb-magento/issues/250#issuecomment-216682904>
>



-- 
-- Sent from my iPhone

**Comment by kylecrum** [comment]
I'll ask other shops but I don't get the sense that this is an issue with any of our current integrators.

**Comment by zztimur** [comment]
It's not an issue, but a feature. So if I implement it, would you merge it via PR?

Also wanted to hear @dunagan5887 take on this.

**Comment by kylecrum** [comment]
That would change how all of the orders work for people who upgrade, so I'm hesitant to do so if people don't seem to want it.

**Comment by skwp** [comment]
If you do implement I would do so as a configuration option so it won't affect existing orders. By default there should be no prefix

**Comment by cpaterso** [comment]
Just confirming that this would be an appreciated feature!  We, like many others, use M2E Pro for eBay and Amazon, and it's nice to have a custom prefix for the channel so that we can sort by channel easily in the admin panel.  Obviously it could be turned on or off just like M2E, so it doesn't hurt anyone who doesn't want to use it.

**Comment by kylecrum** [comment]
Great! We'd happily accept pull requests.
