### ISSUE TITLE
Using Attribute Values from Store View

### ISSUE THREAD

**Issue by cpaterso** [reverbdotcom/reverb-magento#257]
I'm not a developer, but I have experience with M2E Pro and a few other API integrations.

We run a wholesale and a retail site.  Titles, descriptions, and prices are different for each SKU across different store views.  For obvious reasons, we want our retail store view to sync with Reverb.  So far, it seems Reverb is only syncing with the default values, which are not what we want to send.

We've tried disabling the model for the default store view, and enabling the module in the configuration for our Retail store view only.  However, when we try to bulk sync, it says the module is disabled, so this doesn't work.

I see for Order Creation, you can select the store view.  Can something be added to the listing configuration options like "Use Store View: [Select]", so that the attribute values are fetched from the corresponding store view?

**Comment by kylecrum** [comment]
@cpaterso we're happy to accept any pull requests.

**Comment by cpaterso** [comment]
Hi Kylecrum,

Do I need to include coding, or just a suggestion like the above?  (I'm not a developer like I mentioned, so I'm not sure exactly how it would be accomplished.)

**Comment by kylecrum** [comment]
@cpaterso we would need code, yes.

**Comment by cpaterso** [comment]
Unfortunately, I am just a user, not a developer, so I wouldn't know how to implement it or write the code.  But as a store owner, I thought I should make the suggestion since we rely on this type of functionality on our other marketplace API modules (eBay, Amazon, Pricefalls, etc.)  For Magento, it is quite common to have different store views.

We're hoping to set up a Reverb store soon, but will have to wait until (if) something like this is implemented so we can send the correct data.

**Comment by skwp** [comment]
Thanks for your suggestion. If you're looking for professional help to implement your suggestions we recommend these developers: https://github.com/reverbdotcom/reverb-magento#professional-support
