### ISSUE TITLE
Should check memory leak for each created order to ensure that batch size of 100 for creating Reverb orders is small enough

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#26]

**Comment by dunagan5887** [comment]
Each order causes the memory usage of its PHP thread to grow by around 35MB. Given a cap of 100 orders per thread and restricting this process to only spawn 1 thread, it's safe to assume 350MB won't cause issues on production servers.

**Comment by skwp** [comment]
35mb?? why is it so huge ? 

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
That's just the typical memory footprint for a Magento order, due to the amount of event-observer functionality occurring during an order placement, the amount of objects necessary to create an order, and the amount of necessary database calls. Magento didn't really design orders to be created en-masse like this.
