### ISSUE TITLE
Customized reverb 0.9.4 code in Mage EE 1.11.0.0 

### ISSUE THREAD

**Issue by pradeepreddyDev** [reverbdotcom/reverb-magento#260]
Hi,
We got a issue in  magento EE 1.11.0.0. when order is synchronizing from reverb to magento it was showing the error like 
_### 'Mage_CurrencySymbol_Model_System_Currencysymbol' not found in /chroot/home/proaudio/dev.proaudiostar.com/html/app/code/community/Reverb/ReverbSync/Helper/Orders/Creation/Currency.php on line 13_  

we replaced reverb extension code like  Reverb/ReverbSync/Helper/Orders/Creation/Currency.php in function isValidCurrencyCode() we commented the body of the function returned TRUE value

### _public function isValidCurrencyCode($currency_code)
    {
	    //$allowed_currency_symbols_csv_list = Mage::getStoreConfig(Mage_CurrencySymbol_Model_System_Currencysymbol::XML_PATH_ALLOWED_CURRENCIES);
		// $allowed_currency_symbols_array = explode(',', $allowed_currency_symbols_csv_list);
		//  return in_array($currency_code, $allowed_currency_symbols_array);
        return TRUE;
    }_

**Everything is working fine now, Is these piece of code will get conflicted anywhere in the application? please let me know.**

**Comment by kylecrum** [comment]
This would presumably allow any currency on to your magento instance, which is up to you if you want that. I would be more worried that `Mage_CurrencySymbol_Model_System_Currencysymbol` does not exist which is a core Magento class.

**Comment by pradeepreddyDev** [comment]
Hey kylecrum, Thanks for your time.  In **Magento EE** Mage_CurrencySymbol_Model_System_Currencysymbol  we cannot this in core.
