### ISSUE TITLE
Image can't be sync

### ISSUE THREAD

**Issue by minh-pham-niteco** [reverbdotcom/reverb-magento#263]
In magento, the plugin said that the image is sync (http://prntscr.com/crzazo) but I dont see it in reverb site (http://prntscr.com/crzbin). Here is our setting http://prntscr.com/crzb3n, http://prntscr.com/crzb7u
And here is the log file: http://192.249.62.149/demo/Reverb-log.zip

**Comment by kylecrum** [comment]
What is the url of the image?

**Comment by kylecrum** [comment]
@minh-pham-niteco we're getting "Error in loading http://dev.dwmusic.com.au:81/media/catalog/product/c/v/cvp305z.jpg - 403 Forbidden" in our logs. Are you whitelisting certain IPs?

**Comment by minh-pham-niteco** [comment]
@kylecrum , thank you so much to help me. I still can access the image on both computer + laptop (http://prntscr.com/csbe3v) so i dont think the server require IP.

**Comment by kylecrum** [comment]
Well, our servers can't access that image, so there is no way for us to download it to our site.
