### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#33]
Is there a clean way to "uninstall" this extension on boxes that aren't using git for tracking the installation / not using modman? This is a question that came up from one of our customers.

**Comment by dunagan5887** [comment]
No, Magento extensions typically don't come with "uninstall" functionality. Removing them completely would require having a develop go in and remove the files by hand. Another option is to completely disable the module(s) via the config files in app/etc/modules/.
