### ISSUE TITLE
Product sync page is showing wierd embedded visual issue

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#34]
Go to product page, click on "Last synced" column to sort the chart, and get this:

<img width="1168" alt="reverb_reports___reverb_reports___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9826090/4e7ed706-589d-11e5-9bcb-d0a75287cd60.png">

**Comment by skwp** [comment]
The sorting by last synced was working before; this seems like a new bug

**Comment by dunagan5887** [comment]
Currently not seeing this, possible this was a browser issue; what browser are you using? I'm attaching a screenshot of what I currently see on the bitnami instance

<img width="1468" alt="bitname_listing_sync_page" src="https://cloud.githubusercontent.com/assets/1616312/9833539/b968181c-595f-11e5-8cae-9080e1ccc5f6.png">

**Comment by skwp** [comment]
did you try to sort by the last sync column?

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
Now I see it. I'll have to look into this in further depth Monday
