### ISSUE TITLE
0 of 1 orders synced (implement order create/update logs to debug)

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#35]
I made an order, it finally showed up in magento logs:
However the order sync page is showing "0 of 1 synced"
Not sure what that means

<img width="1169" alt="reverb_orders_sync___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9827506/7243d15e-58a8-11e5-8502-dfe83204f265.png">

```
==> var/log/reverb_retrieveOrderCreations.log <==
2015-09-11T22:10:02+00:00 DEBUG (7): 
retrieveOrderCreations
/api/my/orders/selling/all?created_start_date=2015-09-10T15:10:02-00:00&created_end_date=2015-09-11T15:10:02-00:00
200
{"total":1,"_links":{},"orders":[{"amount_product":{"amount":"150.00","currency":"USD","symbol":"$"},"amount_product_subtotal":{"amount":"150.00","currency":"USD","symbol":"$"},"shipping":{"amount":"355.00","currency":"USD","symbol":"$"},"amount_tax":{"amount":"0.00","currency":"USD","symbol":"$"},"total":{"amount":"505.00","currency":"USD","symbol":"$"},"buyer_name":"yan pritzker","created_at":"2015-09-11T09:41:46-05:00","order_number":"223","needs_feedback_for_buyer":true,"needs_feedback_for_seller":true,"order_type":"instant","paid_at":"2015-09-11T09:41:49-05:00","quantity":1,"shipping_address":{"name":"Yan Pritzker c/o Reverb.com","street_address":"3345 N. Lincoln Ave","extended_address":"","locality":"Chicago","region":"IL","postal_code":"60657","country_code":"US","phone":"1231231234"},"local_pickup":false,"shop_name":"Carter Inc","status":"pending_review","title":"QRD Diffusor","updated_at":"2015-09-11T09:41:49-05:00","payment_method":"direct_checkout","_links":{"photo":{"href":"https://reverb-res.cloudinary.com/image/upload/a_exif,c_thumb,f_auto,fl_progressive,g_south,h_192,w_192/v1441824746/bogosszrg387tfe6s9sg.jpg"},"feedback_for_buyer":{"href":"/api/orders/223/feedback/buyer"},"feedback_for_seller":{"href":"/api/orders/223/feedback/seller"},"listing":{"href":"/api/listings/13054"},"start_conversation":{"href":"/api/my/conversations?listing_id=13054\u0026recipient_id=344"},"self":{"href":"/api/my/orders/selling/223"},"mark_picked_up":{"href":"/api/my/orders/selling/223/mark_picked_up"},"contact_buyer":{"web":{"href":"https://sandbox.reverb.com/my/messages/new?item=13054-qrd-diffusor\u0026to=344-yan-p-1\u0026token=59b44b1d06ded7f0e3afb83ed64fec8a2fa7382f7774f214aa1621be6af0cead"}}},"photos":[{"_links":{"large_crop":{"href":"https://reverb-res.cloudinary.com/image/upload/a_exif,c_thumb,f_auto,fl_progressive,g_south,h_640,q_85,w_640/v1441824746/bogosszrg387tfe6s9sg.jpg"},"small_crop":{"href":"https://reverb-res.cloudinary.com/image/upload/a_exif,c_thumb,f_auto,fl_progressive,g_south,h_296,q_85,w_296/v1441824746/bogosszrg387tfe6s9sg.jpg"},"full":{"href":"https://reverb-res.cloudinary.com/image/upload/a_exif,c_limit,f_auto,fl_progressive,h_1136,q_75,w_640/v1441824746/bogosszrg387tfe6s9sg.jpg"},"thumbnail":{"href":"https://reverb-res.cloudinary.com/image/upload/a_exif,c_thumb,f_auto,fl_progressive,g_south,h_192,w_192/v1441824746/bogosszrg387tfe6s9sg.jpg"}}}],"sku":"TEST1","direct_checkout_payout":{"amount":"491.11","currency":"USD","symbol":"$"}}]}
```

**Comment by dunagan5887** [comment]
The issue is logged in var/log/reverb_sync_orders.log:
Exception occurred while trying to create order for reverb order with number 224: This product is currently out of stock.

Looking in the admin panel, the product in question (TEST1) is listed as being out of stock.

**Comment by dunagan5887** [comment]
The real issue here is likely to make it easier for admins to see why order syncs are failing

**Comment by skwp** [comment]
I think the behavior is wrong. regardless of it being out of stock a reverb order was placed. we should show the order regardless of stock status. is this a problem in magento?

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
I would consider this a feature of Magento, not an issue with it; if a product is out of stock, the system doesn't allow an order to be processed as it assumes the store can't fulfill the order. I'll have to check the code to see if there's a way we can supersede this check in the event of a Reverb order

**Comment by skwp** [comment]
yeah we need to find a workaround otherwise people won't know that an order got placed on reverb 

at the very least we need to show an error that provides all the details of the order if there is no workaround 

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
I'll start by creating a grid which displays all of the process_queue items so that users can see the status of the syncing orders

**Comment by skwp** [comment]
great thanks

**Comment by dunagan5887** [comment]
Regarding having order creation/update tasks show up in the same grid, I don't believe that implementing the grid with filter/sort capability would be a task under 8-12 hours.  As such I would again recommend that these exist on two separate pages (Under 2 hours of work due to the abstract code already in place). Another solution is to show them on the same page, but on two different grids, one below the other (experimenting with this now). Let me know what course of action you'd like me to take here.

**Comment by skwp** [comment]
OK to keep them separate if that makes it easier right now. However let's focus today on debugging product sync as I believe it broke. I will be at a conference for the next two days so we need to figure this out today
--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
What's broken with the product sync? While testing on my local it appears to be working from the Magento side

**Comment by skwp** [comment]
What I discussed in #42 - basically I believe that the request going out is incorrect. I'm adding more logging on reverb side to figure out why. I can see the request come in but it does not contain any params
