### ISSUE TITLE
Customer reports revUrl dropdown value Reverb.com is not working with php curl

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#38]
It seems that this customer's installation is sending Reverb.com as the url instead of https://reverb.com from our dropdown

**Comment by dunagan5887** [comment]
Every time I tested this on my local it works, and when I re-saved the configuration on DrumCenter's production instance it fixed the issue. I don't know how this happened and without ssh access there's not much I can do. I would attribute this to issues regarding upgrading from the initial versions

**Comment by skwp** [comment]
Will assume resolved
