### ISSUE TITLE
Custom user-agent

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#39]
Please set the user-agent on all curl requests to "Reverb-Magento". If possible append the current magento version as well, so it would look like "Reverb-Magento MagentoVersion=community-1.9"

If this code is duplicated, please extract to one place

**Comment by dunagan5887** [comment]
Request now looks like this (I forced http to show the request unencrypted):

GET /api/my/listings?state=all&sku=new_curl HTTP/1.1
User-Agent: Reverb-Magento MagentoVersion=community-1.9
Host: sandbox.reverb.com
Accept: */*
X-Auth-Token: 1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c
Content-type: application/hal+json


write error to stdout

HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Date: Wed, 16 Sep 2015 04:54:54 GMT
Location: https://sandbox.reverb.com/api/my/listings?state=all&sku=new_curl
Server: nginx
Content-Length: 178
Connection: keep-alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

write error to stdout
