### ISSUE TITLE
Inventory and orders not syncing on our test instance

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#42]
magento-dev.reverb.com - this is an alias to the old instance, same user/password
We tried to sync inventory both by saving an item (QRD Diffuser) and by bulk sync, no dice. placed an order, it did not come over to magento. Haven't had a chance to look at logs yet.

**Comment by dunagan5887** [comment]
I'm going to finish the admin grid implementation for #35 to alleviate a lot of these questions of why listings/orders aren't syncing

**Comment by skwp** [comment]
thanks do you have an estimate on when that will be done?

Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
Currently working on it now, I'll attach a screenshot. I'm also adding messaging for when listing syncs don't occur due to the module being disabled or a product being set to not sync
<img width="1468" alt="reverb_order_creation_sync_grid" src="https://cloud.githubusercontent.com/assets/1616312/9884877/cd461858-5ba7-11e5-9da7-1cdd1e08a03a.png">

**Comment by dunagan5887** [comment]
Admins will also be allowed to set tasks to be re-tried via this panel:

<img width="1468" alt="update_reverb_order_creation_task" src="https://cloud.githubusercontent.com/assets/1616312/9884910/ffb19272-5ba7-11e5-887e-8a0d982ab104.png">

**Comment by dunagan5887** [comment]
I've currently got the page for Order Creations up and running on my local. Do you want me to implement an analogous page for the order updates?

**Comment by dunagan5887** [comment]
Another option would be for me to put a grid for order updates below the grid for order creations. I would not recommend combining the two grids due to the back-end architecture of the process queue, but it can be done

**Comment by skwp** [comment]
I think combining might be less confusing for customers. if thy want to figure out what happened with a order having to go to two spots to search with it is not good UX. see what you can do about combining but if it's too complicated start with two pages. we can revisit once we have feedback from real customers 

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
Working on allowing clients to prevent access to updating task statuses right now. After that I'll look into combining the two

**Comment by dunagan5887** [comment]
Clients can now restrict access to viewing and modifying the order tasks. I will proceed with combining order creations and updates into the same grid. I will also test this on a new Magento instance as well, since some of the issues to this point have been a result of that case

**Comment by dunagan5887** [comment]
I may not be able to complete the grid combination today just fyi

**Comment by skwp** [comment]
Ok can you please provide a PR for the creation grid if that's done

**Comment by skwp** [comment]
@dunagan5887 I can confirm on my current instance. I just hit bulk sync, I see a successful sync for my product with inventory 5 yet on reverb it is inventory 1. Something doesn't add up.

**Comment by dunagan5887** [comment]
What is the post body being shown in the logs? Is the Reverb "Inventory Tracking" set to "Yes"?

**Comment by skwp** [comment]
it looks like it should be working..
but it's not updating reverb. i'm investigating on our side

==> var/log/reverb_curl_requests.log <==
2015-09-15T22:06:06+00:00 DEBUG (7):
curl -XPUT -H "X-Auth-Token: 59b44b1d06ded7f0e3afb83ed64fec8a2fa7382f7774f214aa1621be6af0cead" https://sandbox.reverb.com/api/listings/13054-qrd-diffusor --data {"title":"QRD Diffusor","sku":"TEST1","condition":"Brand New","has_inventory":"1","inventory":"5.0000","price":"150.0000"}

==> var/log/reverb_updateObject.log <==
2015-09-15T22:06:06+00:00 DEBUG (7):
updateObject
{"title":"QRD Diffusor","sku":"TEST1","condition":"Brand New","has_inventory":"1","inventory":"5.0000","price":"150.0000"}

**Comment by skwp** [comment]
I can confirm that none of the updates are taking. On our side it looks like the params in the API are blank. Is it possible we messed up the content type so they're not reading like they should?

For example, this is wrong:
```
curl -XPUT -H "X-Auth-Token: 59b44b1d06ded7f0e3afb83ed64fec8a2fa7382f7774f214aa1621be6af0cead" https://sandbox.reverb.com/api/listings/13054-qrd-diffusor --data {"title":"QRD Diffusor","sku":"TEST1","condition":"Brand New","has_inventory":"1","inventory":"5.0000","price":"150.0000"}
```

This is Right:
```
curl -XPUT -H "X-Auth-Token: 59b44b1d06ded7f0e3afb83ed64fec8a2fa7382f7774f214aa1621be6af0cead" https://sandbox.reverb.com/api/listings/13054-qrd-diffusor -H "Content-Type: application/hal+json" --data '{"title":"QRD Diffusor","sku":"TEST1","condition":"Brand New","has_inventory":"1","inventory":"5.0000","price":"150.0000"}'
```

The second command executed and worked correctly. I'm not sure if the log is wrong because it's not logging the content-type header or if we're actually not sending the right header.

**Comment by dunagan5887** [comment]
The cURL request log is fairly hard-coded, meaning that the Content-Type is
set (Reverb_ReverbSync_Helper_Data::_getCurlResource() Line 286) even
thought it's not showing in the logs; I'll have to update that logging
method in order to get all headers in there dynamically.

**Comment by dunagan5887** [comment]
I switched the api url to be http so that I could log an unencrypted version of what's being sent from Magento:

GET /api/my/listings?state=all&sku=new_curl HTTP/1.1
Host: sandbox.reverb.com
Accept: */*
X-Auth-Token: 1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c
Content-type: application/hal+json


HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Date: Tue, 15 Sep 2015 22:55:51 GMT
Location: https://sandbox.reverb.com/api/my/listings?state=all&sku=new_curl
Server: nginx
Content-Length: 178
Connection: keep-alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

As you can see, the Content-type is in the header

**Comment by dunagan5887** [comment]
Logging the updateObject PUT request this time:


PUT /api/my/listings?state=all&sku=new_curl HTTP/1.1
Host: sandbox.reverb.com
Accept: */*
Transfer-Encoding: chunked
X-Auth-Token: 1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c
Content-type: application/hal+json
Expect: 100-continue


write error to stdout

HTTP/1.1 100 Continue


write error to stdout

0


write error to stdout

HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Date: Tue, 15 Sep 2015 23:00:39 GMT
Location: https://sandbox.reverb.com/api/my/listings?state=all&sku=new_curl
Server: nginx
Content-Length: 178
Connection: keep-alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

write error to stdout

**Comment by dunagan5887** [comment]
Just realized you were saying that there should NOT be a "Content-Type: application/hal+json" header included, is this correct? Should I remove that header from all API requests?

**Comment by skwp** [comment]
there _should_ be that content type
there is definitely something wrong with the latest version. the requests are seen on reverb but without params. as if the content type is not correctly set. I will try to get more info tomorrow on the raw logs



--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by skwp** [comment]
@dunagan5887 I can definitely confirm there is something wrong with the outbound request from magento. This must have happened when we did the curl cleanup; something got screwed up and we are not correctly sending the params in the PUT requests

This is what a good put request looks like, done from command line curl:
```
{"accept":"*/*","api_version":null,"method":"PUT","query_params":{},"body_params":{"title":"QRD Diffusor","sku":"TEST1","condition":"Brand New","has_inventory":"1","inventory":"5.0000","price":"150.0000"},"path":"/api/listings/13054-qrd-diffusor","remote_addr":"127.0.0.1","request_id":"edacd497-40c1-4808-aff7-09323e8d7ab6","user_agent":"curl/7.43.0","user_id":300,"duration":161,"timestamp":"2015-09-16T16:17:35+00:00","status":200}
```

The ones coming from magento have empty body params:
```
{"accept":"*/*","api_version":null,"method":"PUT","query_params":{},"body_params":null,"path":"/api/listings/13054-qrd-diffusor","remote_addr":"127.0.0.1","request_id":"094715ed-ad8b-49e8-9b6b-e9f7b0d09f01","user_agent":null,"user_id":300,"duration":161,"timestamp":"2015-09-16T16:13:07+00:00","status":200}
```

This is from my server logs. I'm trying to figure out what else might be wrong but I need to modify the logging to show more headers

**Comment by dunagan5887** [comment]
I see the issue now, I'll have a fix for this shortly. Should I commit it with the User-Agent update or on a separate branch?

**Comment by dunagan5887** [comment]
After the new patch:

PUT /api/listings/13437-dsas HTTP/1.1
User-Agent: Reverb-Magento MagentoVersion=Community-1.9.2.0 MagentoDomain=reverb_magento.com
Host: sandbox.reverb.com
Accept: */*
X-Auth-Token: 1ea238014d948d056f189978d7ab837d1c8152112dfcf0d2eca2b2cfd53f7d3c
Content-type: application/hal+json
X-Magento-Version: Community-1.9.2.0
X-Magento-Domain: reverb_magento.com
Content-Length: 123

{"title":"dasdsasdasd","sku":"new_curl","condition":"Used","has_inventory":"1","inventory":"31321.0000","price":"123.4500"}

This one was my fault, a result of not having worked with PUT requests before

**Comment by dunagan5887** [comment]
Just realized issues/github_39 was already merged, I'll create new branches for the PUT and User-Agent issues. Also I'm on Hipchat, would probably be easier to communicate there
