### ISSUE TITLE
Order sync page has listing updates?

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#51]
confused as to why listing_sync jobs are showing up on the order _update_ page (not on creation)

![reverb_order_update_sync_tasks___magento_admin](https://cloud.githubusercontent.com/assets/1731/9915661/e98d1ecc-5c7d-11e5-9312-9e9413f34e9f.png)

**Comment by dunagan5887** [comment]
This is a quick fix, I'll address this now
