### ISSUE TITLE
confusing: tasks in progress vs failed tasks

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#54]
"0 of 3 Reverb Order Creation Tasks have completed syncing with Magento"

I believe this message actually means that 3 tasks completed but they all failed. How can we make this messaging better. Something like:

"5 Tasks In Progress. 1 Task Completed. 2 Tasks Failed"

**Comment by skwp** [comment]
in other words, this screen is permanently stuck in "0 of 3" mode. If that is how it has to be until they clear, we can at least be clear about what' sgoing on by saying "3 failed jobs waiting to retry" or something to that effect

**Comment by dunagan5887** [comment]
Ok, so in terms of mapping statuses to messaging:
Tasks Failed - Aborted status
Tasks Completed - Completed status
Tasks In Progress - Pending/Processing statuses
Tasks waiting retry - Error status

Would this work?

**Comment by skwp** [comment]
yeah I think that's good. Maybe we call "Failed" as "Aborted". That will be clear

**Comment by skwp** [comment]
Tasks Awaiting Retry for the last one. If you have to put this in the "body" area that might make more sense than trying to make that the orange header.

**Comment by dunagan5887** [comment]
Sounds good, I'll show "Failed" instead of "Aborted" as part of issue #49 its a one-line update

**Comment by dunagan5887** [comment]
Have to run but branch issues/github_54 has code committed to it. Haven't fully tested it yet but it looks good.

File skin/adminhtml/default/default/reverb_sync.css allows for updating the css for the messaging. 

NOTE: You'll have to run "modman update-all" after putting this code on the ec2 instance as it creates a new directory that didn't exist in the module to this point
