### ISSUE TITLE
Remove superuser override

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#65]
After talking to some customers, it's better to go back to what we were doing (showing the error state in the queue) rather than overriding the magento protections. If we can make this a setting pretty quickly that would be good, otherwise just undo the superuser override.

**Comment by dunagan5887** [comment]
Any preference on what the label for this setting should be? Otherwise I'm going with:

"Set to "Yes" to ignore all product invntory/availability checks when syncing orders"

**Comment by skwp** [comment]
Yeah that would be fine. The default should be "no". The label should be something like "Override inventory checks" unless you have a better idea

**Comment by dunagan5887** [comment]
I'll make that the label and make mine the comment

**Comment by dunagan5887** [comment]
Making "Override Product Inventory/Status Checks" the label since SuperMode also ignores whether a product is disabled/enabled
