### ISSUE TITLE
Time to wait to reattempt

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#67]
Just remember something relevant. I set the task processor to wait 2 hours after a task has failed to retry the task. This was done so that a task which can't be completed isn't retried every 5 minutes eating up the processor/RAM. Let me know if you want me to update this value

**Comment by dunagan5887** [comment]
@skwp

**Comment by skwp** [comment]
As long as we have a button to manually retry I think that's fine. I assume for the most part customers are going to be manually retrying once they fix the underlying issues
