### ISSUE TITLE
Use fake customer email on orders

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#69]
Orders are currently created without email. Please create orders with this email: [buyer_id]@orders.reverb.com. This is required for many systems that key off the buyer email. I am adding the buyer_id to the order api by tomorrow.

**Comment by dunagan5887** [comment]
Probably 15-45 minutes

**Comment by skwp** [comment]
@dunagan5887 the buyer_id is now part of the reverb API so you should be able to use that to generate this fake email

**Comment by skwp** [comment]
Actually can you make it the MD5 hash of the buyer_id

**Comment by dunagan5887** [comment]
Sounds good

**Comment by dunagan5887** [comment]
Implementing this would likely be around 1-1.5 hours. However testing that the email is correctly sent may require a bit longer, as I wouldn't have access to ensure that the email accounts with [buyer_id]@orders.reverb.com are receiving the emails. 

@skwp  Does the sandbox allow me to view test-customer emails?

**Comment by skwp** [comment]
These are fake email addresses we don't need to ensure that they are receiving. We're just looking to put a fake value in there. So what we want is MD5(buyer_id)@orders.reverb.com
So for example if the buyer_id is 1, we will get something like  b026324c6904b2a9cb4b88d6d61c81d1@orders.reverb.com

The main reason for this is so that  external systems that rely on buyer emails as primary keys will continue to work.

**Comment by dunagan5887** [comment]
Sounds good. Currently I have set the system not to send a customer email via Magento when the order is created. Is this the desired approach, or should I update the extension to send an email upon order creation?

**Comment by skwp** [comment]
Correct it should not send any emails on the magento side

**Comment by dunagan5887** [comment]
In the event that there is no buyer_id on the JSON object, is there a default email the system should use?

**Comment by skwp** [comment]
There will always be a buyer_id but if you want to be defensive you could use unknown@
