### ISSUE TITLE
Add Reverb Order Number to Order invoice in magento

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#70]
Let's get the reverb order number somewhere on the invoice. If it has to be a special field or just part of some other field, I'm open to it. Also the item #  on reverb or even better the link to the item directly.

**Comment by dunagan5887** [comment]
Are we talking about the view invoice screen in the admin panel? Or the email which is sent out upon creation of an invoice?

**Comment by skwp** [comment]
the view invoice screen. thanks 

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
This should be in the range of 30-45 minutes

**Comment by dunagan5887** [comment]
Fortunately this somewhat came as part of #72

**Comment by dunagan5887** [comment]
"Also the item # on reverb or even better the link to the item directly."

This should be created as a separate issue as it will require updates to the order creation process

**Comment by skwp** [comment]
Ok so we can close this?

**Comment by dunagan5887** [comment]
Yes, this can be closed, I've created the separate issue for the item link
