### ISSUE TITLE
Customer name not on order in magento

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#71]
Should be pulled from `order.buyer_name` via reverb

<img width="384" alt="banners_and_alerts_and__000000004___orders___sales___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9961447/3b50f5bc-5de6-11e5-84a8-f916e4531fcd.png">

**Comment by dunagan5887** [comment]
This should be 10-15 minutes
