### ISSUE TITLE
Order: Purchased from section appears nonsensical

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#72]
Should this say "Reverb"?

<img width="566" alt="_000000004___orders___sales___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9961476/6093d29a-5de6-11e5-8540-0e58b89cc519.png">

**Comment by dunagan5887** [comment]
I believe that is just a label placed on the order, so I should be able to update that

**Comment by dunagan5887** [comment]
This should be around 15-20 minutes
