### ISSUE TITLE
Add the Reverb item # and link to the item to the Order Invoice Screen

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#76]
This will require updating the order creation process to record this data on the sales_flat_order_item table

**Comment by dunagan5887** [comment]
Add item link to queue task object and sales_flat_order_item row

**Comment by dunagan5887** [comment]
Estimating 4-5 hours

**Comment by dunagan5887** [comment]
In terms of the link you're referring to here, is this the same $reverb_listing_url that we expect to come back from Reverb_ReverbSync_Helper_Data::findReverbListingUrlByMagentoSku() ? If so, should I record this value in the database on order creation, or should I set the system to dynamically make an API call to fetch this value in the event that it is updated post order-creation?

**Comment by skwp** [comment]
Yes you can record it during creation; it will not change

**Comment by dunagan5887** [comment]
In the event that the findReverbListingUrlByMagentoSku() call fails to return the link during order creation, I'm going to simply leave the field blank on that particular order item. Also in terms of the item #, I'm attaching a screenshot of what's currently coming in as the JSON object. I'm not seeing anyfield that is immediately obvious as an item # (aside from the sku). Which field are you referring to in terms of the item #?


![reverb_order_json_object](https://cloud.githubusercontent.com/assets/1616312/10001601/322b0566-6068-11e5-8d0d-d98d3ead9b84.png)

**Comment by skwp** [comment]
You're right we don't need to show the item # we just need to do the link to it, that would be fine. Also I was thinking we could grab this from Order (`_links.listing.href`) you don't need to fetch it

**Comment by dunagan5887** [comment]
So what I record on the order_item should be:

BASE_URL/_links.listing.href

where  BASE_URL is the value set in configuration? Resulting in something of the form:

https://reverb.com/api/listings/1201

Correct?

**Comment by skwp** [comment]
actually if you set your curl headers to Accept-Version: 2.0 you should get back fully qualified urls (no need for BASE_URL)

**Comment by skwp** [comment]
we  should do that (version 2.0) across the board

**Comment by dunagan5887** [comment]
I'll create a separate issue for the CURL refactor

**Comment by dunagan5887** [comment]
Still getting "/api/listings/1332" back for _links.listing.href. I tried both of the following headers:

Accept: version=2.0
Accept-Version: 2.0

What's the syntax that the Reverb API is expecting?

**Comment by dunagan5887** [comment]
Also, I'm going to make the database field a TEXT field unless you have a varchar limit I should use

**Comment by dunagan5887** [comment]
Currently have this working. Going to merge master into the branch and test on a clean instance before making a pull request. Also I changed my mind again and I'm going to create a separate issue for the Accept-Version: 2.0 header update

**Comment by skwp** [comment]
text should be safe. is that 255 chars?

**Comment by dunagan5887** [comment]
TEXT is unbounded

**Comment by skwp** [comment]
fine with text
