### ISSUE TITLE
Order # on invoice is not the reverb number

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#77]
I think you're showing the magento number not the reverb number which should be like 235 or 236
<img width="613" alt="_000000004___orders___sales___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9967139/65ad57fe-5e06-11e5-9b19-383e53289eaa.png">

**Comment by dunagan5887** [comment]
You're right, I'll patch this quickly
