### ISSUE TITLE
Customer name on Order says "Guest"

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#79]
<img width="576" alt="_000000004___orders___sales___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9967804/79533400-5e0a-11e5-895c-f171cf3ebc1c.png">

Not sure if this was already fixed and this is just due to an old order

**Comment by dunagan5887** [comment]
Due to an old order. Orders placed before the patch will not be updated and will continue to say Guest

**Comment by dhananjayrode123** [comment]
Hey,
How you fixed this issue.
I have also the same issue in my site.

**Comment by skwp** [comment]
@dhananjayrode123 this should not be a problem going forward in new releases

**Comment by TISindiaSupport** [comment]
Can anyone tell me in which case customer name is "Guest"? And how we can get rid of it?

**Comment by kylecrum** [comment]
@TISindiaSupport what version of the plugin are you using?
