### ISSUE TITLE
Do not attempt to update a task queue as processing if status is already processing

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#81]
Due to the requirement of Reverb_ProcessQueue_Model_Mysql4_Task::selectForUpdate() needing to succeed for a queue task to be processed, there currently isn't any danger to the exclusivity of task processing. However, we need to prevent a second execution thread from erroneously updating the last_executed_at time (and eating 2 database queries) if another execution thread has already updated a row for processing

**Comment by dunagan5887** [comment]
Also this would only be liable to occur if an admin manually acted on an order after the cron had already started processing (in this case the Reverb_ProcessQueue_Model_Mysql4_Task::selectForUpdate() query would fail and the manual action would not occur as the cron's execution action would already be occurring). But again, for completeness and correctness, we should make the status check before attempting to update the task as processing

Note: I did not bill any time for this fix

**Comment by skwp** [comment]
much appreciated 

--
Yan Pritzker
yanpritzker.com
via iPhone
