### ISSUE TITLE
Extract PHP Reverb Client from Magento

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#9]
Extract and refactor the current curl code to be a general purpose API client for Reverb. To begin it may implement only the calls we're using here (find by sku and create/update).

Consider using something nicer than curl, like http://guzzle.readthedocs.org/en/latest/

**Comment by dunagan5887** [comment]
Sounds good. Do you have a timeline for when you need this by? I'm going to Riot Fest in Douglas Park this weekend so my bandwidth is a bit hampered this week, but I can get this done by week's end if necessary.

**Comment by skwp** [comment]
This is not critical, next couple weeks. Finishing order sync is critical, and after that image and category sync. This is last on the list thanks Sean

**Comment by skwp** [comment]
not a thing any more, I am going to be generating clients with swagger
