### ISSUE TITLE
Erroneous frontend template files

### ISSUE THREAD

**Issue by dunagan5887** [reverbdotcom/reverb-magento#94]
app/design/frontend/base/default/template/ReverbSync/product/productsync.phtml
app/design/frontend/base/default/template/ReverbSync/product/productfailsync.phtml

These two are legacy template files that don't seem to have a purpose in our codebase currently. Based on what I see, I think the previous developer was failing to add Reverb Product ID and URL to the admin panel view product page. We should remove these files to prevent any confidential data from being view-able by frontend customers. I'm not even seeing any layout updates which would add these to any pages.

In file app/design/adminhtml/default/default/layout/ReverbSync.xml

A tab was created on the admin product edit page. If you go to a product page in the admin panel, you'll see a "Reverb Info" tab. On this tab is a "Sync" button that is not hooked up to an existing controller. Was this a functional spec you had communicated to the previous developer? This would require a new controller action, probably around an hour of work to create the new controller. 

Let me know what resolution you want for these items

**Comment by skwp** [comment]
thanks kill anything that is not working from the prior implementation. this was not part of a spec

--
Yan Pritzker
yanpritzker.com
via iPhone

**Comment by dunagan5887** [comment]
ACL permissions for the Listing Sync page are currently invalid. I created a separate issue for this
